export const TEST_INPUTS = [
    "My name is John Smith and I work at Google in New York",
    "Contact Sarah Johnson at sarah.johnson@microsoft.com",
    "David from Apple visited our office in Paris",
    "Email me at john.smith82@google.com or david.wilson@facebook.com",
    "Contact: sin-markoov@company.com",
    "John and Sarah from Microsoft met David from Google in London",
    "The Apple office in Paris contacted Michael from the New York branch",
    "John sent an email to john.smith@google.com about the Google project",
    "JOHN SMITH works at GOOGLE",
    "john.smith.developer@google.com and smith.john@microsoft.com are both John",
    "Barack Obama was the president of the United States",
    "The Eiffel Tower is located in Paris, France",
    "Amazon's headquarters are in Seattle, Washington",
    "The Great Wall of China is a historic landmark",
    "Angela Merkel was the Chancellor of Germany",
    "The Sydney Opera House is a famous building in Australia",
    "Mount Everest is the highest mountain in the world",
    "The Mona Lisa is displayed in the Louvre Museum in Paris",
    "Tesla, founded by Elon Musk, is based in Palo Alto",
    "The River Nile flows through Egypt and Sudan"
];